### ISSUE TITLE
Error on certificate installation

### ISSUE THREAD

**Issue by Mbugus2008** [beameio/beame-insta-ssl#12]
[2016-12-17 12:16:00] [BeameStore] INFO: Registering credential https://ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.n
et ...
[2016-12-17 12:16:06] [BeameStore] INFO: Credential irhi8wemioxq4nq2.v1.p.beameio.net registered successfully ...
[2016-12-17 12:16:06] [BeameStore] INFO: Credential retrieving auth server creds of ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1
.p.beameio.net...
[2016-12-17 12:16:08] [BeameStore] ERROR: {}
TypeError: done is not a function
    at C:\Users\Paul\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\lib\pem.js:930:17
    at testOpenSSLPath (C:\Users\Paul\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\lib\pem.js:1100:
9)
    at spawnOpenSSL (C:\Users\Paul\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\lib\pem.js:919:5)
    at spawnWrapper (C:\Users\Paul\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\lib\pem.js:1026:5)
    at Object.readCertificateInfo (C:\Users\Paul\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\lib\p
em.js:427:5)
    at Credential.initFromX509 (C:\Users\Paul\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\beame-sdk\sr
c\services\Credential.js:199:7)
    at getRemoteCreds.then.data (C:\Users\Paul\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\beame-sdk\s
rc\services\BeameStoreV2.js:284:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by zglozman** [comment]
please install openssl and add the openssl binary to your system path, and relaunch. 

https://github.com/beameio/beame-insta-ssl look at the readme installing openssl section
