### ISSUE TITLE
SyntaxError: Unexpected token = [node v5.5.0]

### ISSUE THREAD

**Issue by girishfu** [beameio/beame-insta-ssl#13]
Trying to run this but thrown with an error. 

`$ beame-insta-ssl tunnel 8008 http`

```
/Users/girish/.nvm/versions/node/v5.5.0/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/ProxyClient.js:155
createLocalServerConnection(data, callback = nop) {
                                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/girish/.nvm/versions/node/v5.5.0/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameServer.js:8:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by girishfu** [comment]
Updated node [to v7.3.0] fixed the issue! Thanks

**Comment by sophiabeame** [comment]
Thanks for posting the issue here!
