### ISSUE TITLE
beame-insta-ssl create  error

### ISSUE THREAD

**Issue by jlisbz** [beameio/beame-insta-ssl#15]
Hi,

I run beame-insta-ssl create 'the string' but got the error below:

/home/jli/.nvm/versions/node/v5.12.0/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/ProxyClient.js:155
	createLocalServerConnection(data, callback = nop) {
	                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jli/.nvm/versions/node/v5.12.0/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameServer.js:8:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

Can you please help?

Thanks a lot.

JL

**Comment by ilyash** [comment]
Please use NodeJS version 6.9.X (latest stable).

The syntax above is not supported in node versions earlier than 6.
