### ISSUE TITLE
edge server address missing

### ISSUE THREAD

**Issue by jymcheong** [beameio/beame-insta-ssl#21]
Encountered some errors during the create stage:

```
root@misp:/home/misp# beame-insta-ssl create 
'eyJhdXRoVG9rZW4iOiJ7XCJzaWduZWREYXRhXCI6e1wiY3JlYXRlZF9hdFwiOjE0ODY2OTM5NjYsXCJ2YWxpZF90aWxsXCI6MTQ4Njg2Njc2NixcImRhdGFcIjpcIjY0ZGRkY2JjY2I0ZGQ5MjdmNTMxYzNkZDE3NGU2Y2E4ZWUyYTNiNzYyMWZiZDZkZjYzNGY4OGIyNzM1NjEwNjVcIn0sXCJzaWduZWRCeVwiOlwieXB4ZjcyYWtiNm9uanZycS5vaGt2OG9kem53aDVqcHdtLnYxLnAuYmVhbWVpby5uZXRcIixcInNpZ25hdHVyZVwiOlwicHhub1FLZkVnS0cwd2xWMXVLZFMyL0tBZFhESW55cnJVYWw5eUZNcDRSMFJuMUxHeHc3YVNkRThjMGgwTTZkRnA4TjRDMS83MU9NMURPZnBmT3plb1NDRnQrb3RHYXdHTHJLVkp0NUc1ZGR4KzBwb3NpejhrbjVTVUMxM0NiNGZ5SFJ4UWFUUjhXVkFBSXhSQzVlcnl0SkRvY2NtYzVIb1VQTDViTzVJL2lwMjJlMEo4ZDZGbGNnZE85N0hFK3E3MTNwYm9Vb3paMEJIMmZsbFBzZTlZNHJvVTl1RHpWeTUxTXM0dTNIQWxRa2xjbjluUGFRbndIeVA1ZktjWFYzbjZmYTFaaDlUbzJLVUVScmFDU0ZWZk1RdWlWVjltdUYxNlpONHVRVi9jdSsyRjhTVWVwTDRVK2pYb2pOb0VpSmQrTnpFcE9hb1IrdVBuN0ZrYUxibUdRPT1cIn0iLCJuYW1lIjoiSkMiLCJlbWFpbCI6Imp5bWNoZW9uZ0BtZS5jb20iLCJhdXRoU3J2RnFkbiI6InlweGY3MmFrYjZvbmp2cnEub2hrdjhvZHpud2g1anB3bS52MS5wLmJlYW1laW8ubmV0Iiwic3JjIjoyLCJyZWdJZCI6ODI0fQ=='
[2017-02-02 06:09:21] [BeameStore] INFO: Registering credential https://ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net ...
[2017-02-02 06:09:23] [BeameStore] INFO: Credential uhqimednji3nmg9a.v1.p.beameio.net registered successfully ...
[2017-02-02 06:09:23] [BeameStore] INFO: Credential retrieving auth server creds of ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net...
[2017-02-02 06:09:27] [BeameStore] INFO: Signature signed by ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net verified successfully
[2017-02-02 06:09:27] [BeameStore] INFO: Credential auth server creds received for ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net ...
[2017-02-02 06:09:27] [BeameStore] INFO: Credential generating CSR on uhqimednji3nmg9a.v1.p.beameio.net...
[2017-02-02 06:09:27] [BeameStore] INFO: Credential CSR for  uhqimednji3nmg9a.v1.p.beameio.net created successfully...
[2017-02-02 06:09:27] [BeameStore] INFO: Requesting certificates for credential uhqimednji3nmg9a.v1.p.beameio.net ...
[2017-02-02 06:09:32] [BeameStore] INFO: Credential uhqimednji3nmg9a.v1.p.beameio.net certificates received, saving to disk ...
Error: Certificate uhqimednji3nmg9a.v1.p.beameio.net is not valid yet
    at CertificateValidityError (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:71:1)
    at Promise (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1573:12)
    at Credential.checkValidity (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1567:10)
    at checkValidityPromiseHelper (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1585:15)
root@misp:/home/misp# beame-insta-ssl create 'eyJhdXRoVG9rZW4iOiJ7XCJzaWduZWREYXRhXCI6e1wiY3JlYXRlZF9hdFwiOjE0ODY2OTM5NjYsXCJ2YWxpZF90aWxsXCI6MTQ4Njg2Njc2NixcImRhdGFcIjpcIjY0ZGRkY2JjY2I0ZGQ5MjdmNTMxYzNkZDE3NGU2Y2E4ZWUyYTNiNzYyMWZiZDZkZjYzNGY4OGIyNzM1NjEwNjVcIn0sXCJzaWduZWRCeVwiOlwieXB4ZjcyYWtiNm9uanZycS5vaGt2OG9kem53aDVqcHdtLnYxLnAuYmVhbWVpby5uZXRcIixcInNpZ25hdHVyZVwiOlwicHhub1FLZkVnS0cwd2xWMXVLZFMyL0tBZFhESW55cnJVYWw5eUZNcDRSMFJuMUxHeHc3YVNkRThjMGgwTTZkRnA4TjRDMS83MU9NMURPZnBmT3plb1NDRnQrb3RHYXdHTHJLVkp0NUc1ZGR4KzBwb3NpejhrbjVTVUMxM0NiNGZ5SFJ4UWFUUjhXVkFBSXhSQzVlcnl0SkRvY2NtYzVIb1VQTDViTzVJL2lwMjJlMEo4ZDZGbGNnZE85N0hFK3E3MTNwYm9Vb3paMEJIMmZsbFBzZTlZNHJvVTl1RHpWeTUxTXM0dTNIQWxRa2xjbjluUGFRbndIeVA1ZktjWFYzbjZmYTFaaDlUbzJLVUVScmFDU0ZWZk1RdWlWVjltdUYxNlpONHVRVi9jdSsyRjhTVWVwTDRVK2pYb2pOb0VpSmQrTnpFcE9hb1IrdVBuN0ZrYUxibUdRPT1cIn0iLCJuYW1lIjoiSkMiLCJlbWFpbCI6Imp5bWNoZW9uZ0BtZS5jb20iLCJhdXRoU3J2RnFkbiI6InlweGY3MmFrYjZvbmp2cnEub2hrdjhvZHpud2g1anB3bS52MS5wLmJlYW1laW8ubmV0Iiwic3JjIjoyLCJyZWdJZCI6ODI0fQ=='
[2017-02-02 06:09:53] [BeameStore] INFO: Registering credential https://ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net ...
ERROR { message: 'Registration already completed',
  module: 'ProvisionApi',
  data: 
   { status: 500,
     message: 'Registration already completed',
     url: 'https://ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net/node/auth/register',
     postData: 
      { name: 'JC',

```

After which, I was unable to start tunnel:

```
root@misp:/home/misp# beame-insta-ssl tunnel 80 http
Starting tunnel https://uhqimednji3nmg9a.v1.p.beameio.net -> http://localhost:80
Tunnel error: Error: FQDN uhqimednji3nmg9a.v1.p.beameio.net can not be used for tunnel - edge server address missing
```

**Comment by jymcheong** [comment]
Did some further test cases. 

Creating from on my mac vs within my VM. Registration (cert ... edge creation) works smoothly on mac which has npm4.0.5 & node7.4.0. 

While inside the VM ubuntu 1404 which has npm3.10.10 & node6.9.5 failed repeatedly (registered email to create cert) twice. Interesting.

**Comment by jymcheong** [comment]
upgraded the node to 7.5.0, still no joy:
```
root@misp:/home/misp# node -v
v7.5.0
root@misp:/home/misp# beame-insta-ssl create 'eyJhdXRoVG9rZW4iOiJ7XCJzaWduZWREYXRhXCI6e1wiY3JlYXRlZF9hdFwiOjE0ODY2OTY4ODgsXCJ2YWxpZF90aWxsXCI6MTQ4Njg2OTY4OCxcImRhdGFcIjpcImEwMGU2ODZlNTFmOWM0ODYwNWQ0OGQ5ODZmYmJlNTUzMTc5YWU2NzFjODE2NDYyMjFlY2ExYTI2ZWI5ZGFmOWRcIn0sXCJzaWduZWRCeVwiOlwieXB4ZjcyYWtiNm9uanZycS5vaGt2OG9kem53aDVqcHdtLnYxLnAuYmVhbWVpby5uZXRcIixcInNpZ25hdHVyZVwiOlwiTmVWRmlrazVjMGlMZjFjRFBEZjlaVTlDRmpJTTY4ZGxOVkRsTlR1VlVPbTlGRkpuelM1Ylh2c3Btb1VjUVZFMmEzeUE3eURIWWV2ZnFYdTVZNW55ZzgxbDFjQTJVTFc2UXplVmNSbnNydHNqRW96d0w1TSthaHZlbGlSTkZZU1pIMis1NG5BWWxkak50dm11ejNjUk9WTy9KenZmcCtxQmNyLzJpZklDOWQ4ZnN2MHhXeDZ0dW51aXlUTDNMOUhZd0lrTG1GMkRKSHBvRnFJdHlmbzlXTzZKczFvQVN5NjN0cmxZVW10N012QkRyQjFNWXl1VWozeDhWUmlzc1g5SjhQRVV5NmVUNzRkaVJYdWJJQ0dJMjhLQ1c4eXFqd24xUFN2MXB5eW41RS9NNmdrRGFIeGltQVgzUGtPbDlKWEpLL202R285Z2JJeldyTjFYVkhOZmRnPT1cIn0iLCJuYW1lIjoidGVzdGJlYW1pbzNyZEBtYWlsaW5hdG9yLmNvbSIsImVtYWlsIjoidGVzdGJlYW1pbzNyZEBtYWlsaW5hdG9yLmNvbSIsImF1dGhTcnZGcWRuIjoieXB4ZjcyYWtiNm9uanZycS5vaGt2OG9kem53aDVqcHdtLnYxLnAuYmVhbWVpby5uZXQiLCJzcmMiOjIsInJlZ0lkIjo4Mjh9'
(node:20525) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:20525) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:20525) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:20525) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:20525) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:20525) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:20525) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:20525) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[2017-02-02 06:56:33] [BeameStore] INFO: Registering credential https://ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net ...
[2017-02-02 06:56:45] [BeameStore] INFO: Credential ktna97zjfvw8fgyy.v1.p.beameio.net registered successfully ...
[2017-02-02 06:56:45] [BeameStore] INFO: Credential retrieving auth server creds of ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net...
[2017-02-02 06:56:45] [BeameStore] INFO: Signature signed by ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net verified successfully
[2017-02-02 06:56:45] [BeameStore] INFO: Credential auth server creds received for ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net ...
[2017-02-02 06:56:45] [BeameStore] INFO: Credential generating CSR on ktna97zjfvw8fgyy.v1.p.beameio.net...
[2017-02-02 06:56:45] [BeameStore] INFO: Credential CSR for  ktna97zjfvw8fgyy.v1.p.beameio.net created successfully...
(node:20525) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:20525) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:20525) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[2017-02-02 06:56:45] [BeameStore] INFO: Requesting certificates for credential ktna97zjfvw8fgyy.v1.p.beameio.net ...
[2017-02-02 06:56:49] [BeameStore] INFO: Credential ktna97zjfvw8fgyy.v1.p.beameio.net certificates received, saving to disk ...
(node:20525) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:20525) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Error: Certificate ktna97zjfvw8fgyy.v1.p.beameio.net is not valid yet
    at Promise (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1573:12)
    at Credential.checkValidity (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1567:10)
    at checkValidityPromiseHelper (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1585:15)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by jymcheong** [comment]
Changed the VM to bridge mode, works.
