### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by kupouzar** [beameio/beame-insta-ssl#22]
Can't run (Ubuntu X64)
$ beame-insta-ssl

/usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameStoreV2.js:106
	find(fqdn, allowRemote=true) {
	                      ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/cli/creds.js:13:21)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by zglozman** [comment]
You need to upgrade nodejs to 6.9.x

**Comment by hermandinho** [comment]
💯

**Comment by zglozman** [comment]
Update node to 6.9.X
