### ISSUE TITLE
[BeameInstaSSL] FATAL: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by monte-hayward** [beameio/beame-insta-ssl#37]
Hi. I signed up and followed the email command. v 1.1.9

```
cd /work
beame-insta-ssl creds getCreds --regToken 'eyJhdXR ... entire token'

[2017-04-26 15:01:36] [BeameStore] INFO: Registering credential https://ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net ...
[2017-04-26 15:01:37] [BeameStore] INFO: Credential l7bh063ff6vk2vq5.v1.p.beameio.net registered successfully ...
[2017-04-26 15:01:37] [BeameStore] INFO: Credential retrieving auth server creds of ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net...
[2017-04-26 15:01:37] [BeameStore] ERROR: set expiration status error TypeError: Cannot read property 'end' of undefined
[2017-04-26 15:01:37] [BeameStore] ERROR: Path must be a string. Received undefined
[2017-04-26 15:01:37] [BeameInstaSSL] ERROR: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at BeameStoreDataServices.writeObject (/Users/monte/.node_modules_global/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameStoreDataServices.js:57:25)
    at pem.readCertificateInfo (/Users/monte/.node_modules_global/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:234:29)
    at fetchCertificateData (/Users/monte/.node_modules_global/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:812:5)
    at /Users/monte/.node_modules_global/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:432:16
    at /Users/monte/.node_modules_global/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1031:9
    at /Users/monte/.node_modules_global/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:940:13
    at testOpenSSLPath (/Users/monte/.node_modules_global/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1101:9)
    at spawnOpenSSL (/Users/monte/.node_modules_global/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:920:5)
[2017-04-26 15:01:37] [BeameInstaSSL] FATAL: Path must be a string. Received undefined
```

installed:

```
 npm install -g beame-insta-ssl
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/Users/monte/.node_modules_global/bin/beame-insta-ssl -> /Users/monte/.node_modules_global/lib/node_modules/beame-insta-ssl/main.js
/Users/monte/.node_modules_global/lib
└─┬ beame-insta-ssl@1.1.9
...
```

**Comment by zglozman** [comment]
Openssl is missing pls install it and add it to system path
