### ISSUE TITLE
Renew expired certificate

### ISSUE THREAD

**Issue by samuelgh** [beameio/beame-insta-ssl#38]
Is it possible to renew a certificate? 

<img width="457" alt="certificate" src="https://cloud.githubusercontent.com/assets/6417650/25541392/c401437a-2c4e-11e7-874f-d95de4692b0b.png">

Also, the validity time is very short. Is it possible to alter these values?

**Comment by zglozman** [comment]
update ur beame-insta-ssl with npm update -g beame-insta-gatekeeper.

then run beame-insta-ssl creds renewCert --fqdn 'urfqdn'
beame-insta-ssl creds to verify the

**Comment by samuelgh** [comment]
Thanks for the info, but it doesn't seem to work with an expired certificate, or am I doing something wrong?

```
beame-insta-ssl creds renewCert --fqdn 'xkkz29hvupuopgx7.v1.p.beameio.net'
[2017-04-29 08:23:28] [BeameInstaSSL] ERROR: Error: Certificate xkkz29hvupuopgx7.v1.p.beameio.net has expired
    at CertificateValidityError (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:82:3)
    at Promise (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1813:12)
    at Credential.checkValidity (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1803:10)
    at _onCredFound (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameStoreV2.js:138:17)
    at Promise (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameStoreV2.js:146:6)
    at BeameStoreV2.find (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameStoreV2.js:110:10)
    at Promise (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1170:16)
    at Credential.renewCert (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1169:10)
    at renewCert (/usr/local/lib/node_modules/beame-insta-ssl/cli/creds.js:246:36)
    at main (/usr/local/lib/node_modules/beame-insta-ssl/cli/beame.js:323:33)
[2017-04-29 08:23:28] [BeameInstaSSL] FATAL: Certificate xkkz29hvupuopgx7.v1.p.beameio.net has expired
```

**Comment by samuelgh** [comment]
ping @zglozman

**Comment by AlexzxelA** [comment]
in current release, there's no exposed API to renew L0 certificate on client side. We will take care of it. If you don't need that particular fqdn you are welcome to request a new one at https://ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net/insta-ssl
