### ISSUE TITLE
Beame update not working

### ISSUE THREAD

**Issue by JulianNorton** [beameio/beame-insta-ssl#40]
1. `sudo npm update -g beame-insta-ssl beame-insta-ssl creds renewCert --fqdn 'urfqdn'`

2.  `beame-insta-ssl tunnel 8080 http` I'm still getting the "certificate expired error".

When I just try the renewCert command I get:

> [BeameInstaSSL] FATAL: Credential fqdn was not found locally and allowRemote is false

**Comment by zenit1** [comment]
Hey Julian

Your certificate has been expired and you need authorization token to renew expired certificate.
I can email it to you. Please confirm that your email is j***n@gmal.com.

**Comment by JulianNorton** [comment]
That's either a typo on your end or mine, it should be Gmail.

**Comment by zenit1** [comment]
Please check email

**Comment by JulianNorton** [comment]
`beame command not found` so I tried with `beame-insta-ssl`
```

 beame-insta-ssl creds renewCert --signerAuthToken [redacted]== --fqdn [redacted].v1.p.beameio.net
(node:15850) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:15850) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:15850) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:15850) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[2017-05-04 09:11:17] [BeameInstaSSL] ERROR: Error: Certificate [redacted].v1.p.beameio.net has expired
    at Promise (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1813:12)
    at Credential.checkValidity (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1803:10)
    at _onCredFound (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameStoreV2.js:138:17)
    at Promise (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameStoreV2.js:146:6)
    at BeameStoreV2.find (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameStoreV2.js:110:10)
    at Promise (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1170:16)
    at Credential.renewCert (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1169:10)
    at renewCert (/usr/lib/node_modules/beame-insta-ssl/cli/creds.js:246:36)
    at main (/usr/lib/node_modules/beame-insta-ssl/cli/beame.js:323:33)
    at Object.<anonymous> (/usr/lib/node_modules/beame-insta-ssl/main.js:6:1)
[2017-05-04 09:11:17] [BeameInstaSSL] FATAL: Certificate [redacted].v1.p.beameio.net has expired
```

Copying our conversation here should anyone need help with this specific issue in the future.

**Comment by ilyash** [comment]
Closing because it's solved, if I understand correctly. Feel free to re-open if you need anything.
