### ISSUE TITLE
Fresh Install Issues

### ISSUE THREAD

**Issue by haylinmoore** [beameio/beame-insta-ssl#45]
I just ran npm install -g beame-insta-ssl

then got

root@raspberrypi:~# beame-insta-ssl
/usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/utils/CommonUtils.js:206
	static validateMachineClock(fuzz,retries = 3) {
	                                         ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/utils/Logger.js:8:21)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by zglozman** [comment]
Upgrade you nodejs
