### ISSUE TITLE
Moving certificates from a Mac to Windows PC

### ISSUE THREAD

**Issue by stephan1827** [beameio/beame-insta-ssl#5]
I am trying to transfer the certificate to my Windows machine where it is supposed to run in the future. I tried to use the email with certificate but that gives me an error because it is already installed. Then I used the export command on my Mac but I have no idea how to import it on the Windows machine. There is no import command and the files look different than the files in .beamio directory. I then tried to copy the files from the .beameio directory to the windows machine but when I try to start the service it gives me an error

TypeError: Cannot read property 'commonName' of undefined
    at pem.readCertificateInfo (C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\beame-sd
k\src\services\Credential.js:155:44)
    at C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\lib\pem.js:429:20
    at C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\lib\pem.js:1030:9
    at C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\lib\pem.js:921:20
    at testOpenSSLPath (C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\lib\pem.js:1
098:13)
    at spawnOpenSSL (C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\lib\pem.js:919:
5)
    at spawnWrapper (C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\lib\pem.js:1026
:5)
    at Object.readCertificateInfo (C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\l
ib\pem.js:427:5)
    at Credential.initCryptoKeys (C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\beame-
sdk\src\services\Credential.js:154:8)
    at Credential.initFromData (C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\beame-sd
k\src\services\Credential.js:145:8)

**Comment by stephan1827** [comment]
I installed openSSL and it started working fine.

Stephan
