### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by Baaleos** [beameio/beame-insta-ssl#51]
Trying to register- unfortunately when pasting the command from the registration email into powershell or cmd - I get:

\node_modules\beame-insta-ssl\node_module
s\beame-sdk\src\utils\CommonUtils.js:206
        static validateMachineClock(fuzz,retries = 3) {
                                                 ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\jrolleston\AppData\Roaming\npm\node_modules\
beame-insta-ssl\node_modules\beame-sdk\src\utils\Logger.js:8:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

Its a pity, I was looking for a service that could provide reverse proxy functionality for selenium, guess I will keep looking in the meantime.

**Comment by ilyash** [comment]
Please make sure that you are using Node.js version 6.
