### ISSUE TITLE
Error: expired cert, can't renew

### ISSUE THREAD

**Issue by elimisteve** [beameio/beame-insta-ssl#52]
Should I just start over?...

```
steve@zenbook:~$ beame-insta-ssl creds list
┌───────────────────────────────────┬───────────────────────────────────────────────────────┬───────────────────────────────────────────────────────┬─────────────────────────┬──────────┐
│ name                              │ fqdn                                                  │ parent                                                │ valid                   │ priv/k   │
├───────────────────────────────────┼───────────────────────────────────────────────────────┼───────────────────────────────────────────────────────┼─────────────────────────┼──────────┤
│ Steve Phillips                    │ tb8oyhthhne9m9kz.v1.p.beameio.net                     │                                                       │ 4/14/2017, 9:55:00 PM   │ Y        │
└───────────────────────────────────┴───────────────────────────────────────────────────────┴───────────────────────────────────────────────────────┴─────────────────────────┴──────────┘
steve@zenbook:~$ beame-insta-ssl creds renewCert --fqdn tb8oyhthhne9m9kz.v1.p.beameio.net
[2017-11-19 21:07:18] [BeameCreds] INFO: Trying to renew tb8oyhthhne9m9kz.v1.p.beameio.net
Picking next parent
[2017-11-19 21:07:18] [BIS-Credentials] ERROR: Failed to find valid signer cred for tb8oyhthhne9m9kz.v1.p.beameio.net
steve@zenbook:~$ beame-insta-ssl tunnel make --dst 8082 --proto http
Starting tunnel https://tb8oyhthhne9m9kz.v1.p.beameio.net -> http://localhost:8082
[2017-11-19 21:07:34] [BeameStore] ERROR: Error: Certificate tb8oyhthhne9m9kz.v1.p.beameio.net has expired
[2017-11-19 21:07:34] [BeameStore] ERROR:     at CertificateValidityError (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:95:3)
[2017-11-19 21:07:34] [BeameStore] ERROR:     at Promise (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:2577:12)
[2017-11-19 21:07:34] [BeameStore] ERROR:     at Credential.checkValidity (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:2567:10)
[2017-11-19 21:07:34] [BeameStore] ERROR:     at credential (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameStoreV2.js:247:18)
[2017-11-19 21:07:34] [BeameStore] ERROR:     at Promise (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameStoreV2.js:258:6)
[2017-11-19 21:07:34] [BeameStore] ERROR:     at BeameStoreV2.find (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameStoreV2.js:206:10)
[2017-11-19 21:07:34] [BeameStore] ERROR:     at Promise (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1991:16)
[2017-11-19 21:07:34] [BeameStore] ERROR:     at Credential.setDns (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1979:10)
[2017-11-19 21:07:34] [BeameStore] ERROR:     at Promise (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:2101:10)
[2017-11-19 21:07:34] [BeameStore] ERROR:     at Credential.getDnsValue (/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:2095:10)
[2017-11-19 21:07:34] [ProxyClient] ERROR: Get dns error for tb8oyhthhne9m9kz.v1.p.beameio.net Unexpected error. SERVER NOT STARTED
```

**Comment by ilyash** [comment]
Hi!
Yes, you can't renew because you can't sign renew request with expired credentials.
Sorry for the delay.
