### ISSUE TITLE
Can not register on Windows 10

### ISSUE THREAD

**Issue by stephan1827** [beameio/beame-insta-ssl#6]
Hi,
I am trying to register a new service but I get an error during the registration process

[2016-11-16 19:40:38] [BeameStore] ERROR: {}
ERROR TypeError: done is not a function
    at C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\lib\pem.js:930:17
    at testOpenSSLPath (C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\lib\pem.js:1100:9)
    at spawnOpenSSL (C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\lib\pem.js:919:5)
    at spawnWrapper (C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\lib\pem.js:1026:5)
    at Object.readCertificateInfo (C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\pem\lib\pem.j
27:5)
    at Credential.initFromX509 (C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\beame-sdk\src\se
ces\Credential.js:188:7)
    at getRemoteCreds.then.data (C:\Users\Media PC\AppData\Roaming\npm\node_modules\beame-insta-ssl\node_modules\beame-sdk\src\s
ices\BeameStoreV2.js:266:19)
    at process._tickCallback (internal/process/next_tick.js:103:7)

These are my installed versions

PS C:\WINDOWS\system32> npm version
{ npm: '3.10.9',
  ares: '1.10.1-DEV',
  cldr: '30.0.2',
  http_parser: '2.7.0',
  icu: '58.1',
  modules: '51',
  node: '7.1.0',
  openssl: '1.0.2j',
  tz: '2016g',
  unicode: '9.0',
  uv: '1.10.0',
  v8: '5.4.500.36',
  zlib: '1.2.8' }

**Comment by zglozman** [comment]
looks like an openssl issue

**Comment by zglozman** [comment]
do u have openssl installed and in the system path ?

**Comment by stephan1827** [comment]
You are correct. I installed openSSL and it started working fine.

Stephan
