### ISSUE TITLE
[install] Callback must be a function

### ISSUE THREAD

**Issue by ghost** [beameio/beame-insta-ssl#60]
Fresh install of Node (via `nvm`) on Fedora 28.

```sh
node --version
v10.1.0
```

```sh
beame-insta-ssl creds getCreds --regToken eyJhdXRoVG9rZW4iOiJ7XCJzaWduZWRE.....

...

[2018-05-21 08:38:46] [BeameStore] INFO: Credential retrieving auth server creds of [XXXXXX].v1.p.beameio.net...
[2018-05-21 08:38:47] [BeameStore] ERROR: Callback must be a function
[2018-05-21 08:38:47] [BeameInstaSSL] ERROR: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:148:11)
    at Object.fs.unlink (fs.js:1016:14)
    at /home/[user]/.nvm/versions/node/v10.1.0/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1029:16
    at Array.forEach (<anonymous>)
    at /home/[user]/.nvm/versions/node/v10.1.0/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1028:15
    at /home/[user]/.nvm/versions/node/v10.1.0/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:940:13
    at testOpenSSLPath (/home/[user]/.nvm/versions/node/v10.1.0/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1101:9)
    at spawnOpenSSL (/home/[user]/.nvm/versions/node/v10.1.0/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:920:5)
    at spawnWrapper (/home/[user]/.nvm/versions/node/v10.1.0/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1027:5)
    at Object.readCertificateInfo (/home/[user]/.nvm/versions/node/v10.1.0/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:428:5)
[2018-05-21 08:38:47] [BeameInstaSSL] FATAL: Callback must be a function
```

**Comment by CSRaghunandan** [comment]
I'm having the same problem as well. I'm on macOS High sierra using node `v10.1.0`.

Any idea how we can fix this?

**Comment by iborysenko** [comment]
`Ubuntu 18.04`  `v10.1.0` same issue

**Comment by Hurlu** [comment]
Windows 10 here, same problem, tried installing OpenSSL with the instructions in the readme and using an installer (https://slproweb.com/products/Win32OpenSSL.html), same problem.

**Comment by chetan-objectedge** [comment]
same issue 
Mac high sierra, node v : V10.4.1

[BeameStore] INFO: Credential retrieving auth server creds of ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net...
[2018-06-20 12:53:38] [BeameStore] ERROR: Callback must be a function
[2018-06-20 12:53:38] [BeameInstaSSL] ERROR: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:167:11)
    at Object.fs.unlink (fs.js:1036:14)
    at /Users/r0ck3t_m/.nvm/versions/node/v10.4.1/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1029:16
    at Array.forEach (<anonymous>)
    at /Users/r0ck3t_m/.nvm/versions/node/v10.4.1/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1028:15
    at /Users/r0ck3t_m/.nvm/versions/node/v10.4.1/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:940:13
    at testOpenSSLPath (/Users/r0ck3t_m/.nvm/versions/node/v10.4.1/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1101:9)
    at spawnOpenSSL (/Users/r0ck3t_m/.nvm/versions/node/v10.4.1/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:920:5)
    at spawnWrapper (/Users/r0ck3t_m/.nvm/versions/node/v10.4.1/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1027:5)
    at Object.readCertificateInfo (/Users/r0ck3t_m/.nvm/versions/node/v10.4.1/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:428:5)
[2018-06-20 12:53:38] [BeameInstaSSL] FATAL: Callback must be a function

**Comment by BobbyAdamson** [comment]
Same issue. Mac High Sierra, Node 10.1.0. Only way I can get credentials is to switch to an earlier version of node (coworker uses 6.11.1 so I installed and switched via nvm and it worked fine).

**Comment by ldenis2** [comment]
Same issue on Node 10.8.0.
 To fix the issue I installed latest pem package globally using
'npm i -g pem'
and than removed pem package from node_modules folder of beame-insta-ssl. Then beame-insta-ssl works fine with Node 10.8.0 in tunnel mode.

Please fix the issue by including latest pem module in beame-insta-ssl package.

**Comment by jwulf** [comment]
When I do this, I get this error:

```
2018-08-25 19:17:22] [BeameStore] ERROR: Cannot read property 'setFolder' of undefined
[2018-08-25 19:17:22] [BeameInstaSSL] ERROR: TypeError: Cannot read property 'setFolder' of undefined
    at Credential.initFromX509 (/opt/nodejs/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:349:27)
    at getRemoteCreds.then.data (/opt/nodejs/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameStoreV2.js:502:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2018-08-25 19:17:22] [BeameInstaSSL] FATAL: Cannot read property 'setFolder' of undefined
```

**Comment by ldenis2** [comment]
> When I do this, I get this error:

Seems like you have not configured beame-insta-ssl properly.
 Do you have OpenSSL installed?

And looks like you are running beame-insta-ssl on linux while I am running it on Win10...

**Comment by BenRomberg** [comment]
The following command fixed it for me (Ubuntu 18.04):
```
/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk$ sudo npm install pem@1.12.5
```

Make sure to run this inside the `beame-sdk` directory, running it in the `beame-insta-ssl` directory didn't fix it (but also didn't hurt).

**Comment by nicely** [comment]
@BenRomberg   FATAL: Cannot read property 'setFolder' of undefined. This is new erroe :)

**Comment by niels** [comment]
@nicely beame uses a customized `pem` version. Upstream versions like `1.12.5` as referenced further above will not work. Instead, use `https://github.com/beameio/pem/archive/v1.8.4.tar.gz`; for example, like so:

```bash
/usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk$ sudo npm install pem@https://github.com/beameio/pem/archive/v1.8.4.tar.gz
```

**Comment by sunnysai12345** [comment]
@niels This fixed the issue Thanks.

**Comment by wildsurfer** [comment]
Same problem on macos mojave

```
[2019-02-28 14:46:32] [BeameInstaSSL] ERROR: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:144:11)
    at Object.unlink (fs.js:962:14)
    at /usr/local/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1029:16
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1028:15
    at /usr/local/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:940:13
    at testOpenSSLPath (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1101:9)
    at spawnOpenSSL (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:920:5)
    at spawnWrapper (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1027:5)
    at Object.readCertificateInfo (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:428:5)
[2019-02-28 14:46:32] [BeameInstaSSL] FATAL: Callback must be a function
```

**Comment by wpa** [comment]
MacOS mojave.
node v11.9.0
 [BeameInstaSSL] ERROR: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:142:11)
    at Object.unlink (fs.js:960:14)

**Comment by tlohyk** [comment]
On Windows 10, i performed the following and solved this problem.

**Under this path, run the npm command.**
C:\Users\{username}\AppData\Roaming\npm\node_modules\beame-insta-ssl> npm install pem@https://github.com/beameio/pem/archive/v1.8.4.tar.gz

**Follow the recommendation to run npm audit fix**
C:\Users\{username}\AppData\Roaming\npm\node_modules\beame-insta-ssl> npm audit fix

After the above completed, I re-run the regToken command and it was successful.

**Comment by organom** [comment]
Hi all, 
Sorry for the late reply on this one.
The missing dependency was added to the dev branch and can be tried from there until the next release (that should happen during the next weeks).

**Comment by ldenis2** [comment]
hi all, I fixed all the tunnel related stuff in my fork. This version works with latest pem module and latest nodejs (13.6). If you would like to test this version you can run 'npm -g i github:ldenis2/beame-insta-ssl'. To make npm work, you need github client installed on your machine.

**Comment by easysoft-mobility** [comment]
> @nicely beame uses a customized `pem` version. Upstream versions like `1.12.5` as referenced further above will not work. Instead, use `https://github.com/beameio/pem/archive/v1.8.4.tar.gz`; for example, like so:
> 
> ```shell
> /usr/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk$ sudo npm install pem@https://github.com/beameio/pem/archive/v1.8.4.tar.gz
> ```

worked for me in Ubuntu 18.04 TLS

**Comment by organom** [comment]
> hi all, I fixed all the tunnel related stuff in my fork. This version works with latest pem module and latest nodejs (13.6). If you would like to test this version you can run 'npm -g i github:ldenis2/beame-insta-ssl'. To make npm work, you need github client installed on your machine.

Using the latest pem with beame-sdk will not work correctly since the beame-sdk - BeameStoreV2 expects the certificates to be load synchronously, on start, and the methods used from the Pem library are asynchronous. We're trying to address this for the next beame-sdk release and hopefully remove the need for the custom pem implementation.

**Comment by ldenis2** [comment]
> Using the latest pem with beame-sdk will not work correctly since the beame-sdk - BeameStoreV2 expects the certificates to be load synchronously, on start, and the methods used from the Pem library are asynchronous. We're trying to address this for the next beame-sdk release and hopefully remove the need for the custom pem implementation.

But it works since I fixed it in beame-sdk as well. My beame-insta-ssl is linked to my  beame-sdk fork. You can check it here https://github.com/ldenis2/beame-sdk

**Comment by bxff** [comment]
MacOS users: 
```
cd /usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk; sudo npm install pem@https://github.com/beameio/pem/archive/v1.8.4.tar.gz
```
