### ISSUE TITLE
Cannot read property 'setFolder' of undefined

### ISSUE THREAD

**Issue by nicely** [beameio/beame-insta-ssl#66]
```Cannot read property 'setFolder' of undefined
    at Credential.initFromX509 (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:349:27)
    at getRemoteCreds.then.data (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameStoreV2.js:502:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2018-09-18 15:31:51] [BeameInstaSSL] FATAL: Cannot read property 'setFolder' of undefined```


I'm trying to `beame-insta-ssl creds getCreds --regToken.  09ı1290dıu912ud01du10du28128` registeer token but I get this error :/

**Comment by ilyash-b** [comment]
Reopen if still relevant
