### ISSUE TITLE
TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by MmtBkn** [beameio/beame-insta-ssl#69]
Hello,

I'm getting following error when I run;

`beame-insta-ssl tunnel make --dst 4200 --proto http`

```
[2018-11-15 18:32:25] [BeameStore] ERROR: TypeError: Cannot read property 'start' of undefined
[2018-11-15 18:32:25] [BeameStore] ERROR:     at Promise (/Users/m/.nvm/versions/node/v6.14.4/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:2569:76)
[2018-11-15 18:32:25] [BeameStore] ERROR:     at Credential.checkValidity (/Users/m/.nvm/versions/node/v6.14.4/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:2567:10)
[2018-11-15 18:32:25] [BeameStore] ERROR:     at _onCredFound (/Users/m/.nvm/versions/node/v6.14.4/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameStoreV2.js:247:18)
[2018-11-15 18:32:25] [BeameStore] ERROR:     at Promise (/Users/m/.nvm/versions/node/v6.14.4/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameStoreV2.js:258:6)
[2018-11-15 18:32:25] [BeameStore] ERROR:     at BeameStoreV2.find (/Users/m/.nvm/versions/node/v6.14.4/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameStoreV2.js:206:10)
[2018-11-15 18:32:25] [BeameStore] ERROR:     at Promise (/Users/m/.nvm/versions/node/v6.14.4/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1991:16)
[2018-11-15 18:32:25] [BeameStore] ERROR:     at Credential.setDns (/Users/m/.nvm/versions/node/v6.14.4/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:1979:10)
[2018-11-15 18:32:25] [BeameStore] ERROR:     at Promise (/Users/m/.nvm/versions/node/v6.14.4/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:2101:10)
[2018-11-15 18:32:25] [BeameStore] ERROR:     at Credential.getDnsValue (/Users/m/.nvm/versions/node/v6.14.4/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/Credential.js:2095:10)
[2018-11-15 18:32:25] [BeameStore] ERROR:     at Promise (/Users/m/.nvm/versions/node/v6.14.4/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/ProxyClient.js:91:16)
[2018-11-15 18:32:25] [ProxyClient] ERROR: Get dns error for onmt2i7452yskmlz.v1.p.beameio.net Unexpected error. SERVER NOT STARTED
(node:7103) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Error starting HTTPS terminating proxy: undefined
```

Node v6.14.4
MacOS v10.14.1

**Comment by ilyash-b** [comment]
Reopen if still relevant
