### ISSUE TITLE
ERROR: Callback must be a function. Received undefined

### ISSUE THREAD

**Issue by avaleriani** [beameio/beame-insta-ssl#85]
Hey! 

I'm trying to run it on a computer without sudo access and when I copied and paste the email command I'm getting this error, can somebody help me to understand what's going on?

The os version is: 

> Linux 0f1a394142c3 4.15.0-107-generic #108~16.04.1-Ubuntu SMP Fri Jun 12 02:57:13 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```
beame-insta-ssl creds getCreds --regToken <token>
[2020-07-10 20:19:43] [BeameStore] INFO: Registering credential https://<url>.ohkv8odznwh5jpwm.v1.p.beameio.net ...

[2020-07-10 20:19:44] [BeameStore] INFO: Credential <url>.v1.p.beameio.net registered successfully ...

[2020-07-10 20:19:44] [BeameStore] INFO: Credential retrieving auth server creds of <url>.ohkv8odznwh5jpwm.v1.p.beameio.net...

[2020-07-10 20:19:45] [BeameStore] ERROR: Callback must be a function. Received undefined

[2020-07-10 20:19:45] [BeameInstaSSL] ERROR: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. 
Received undefined

    at makeCallback (fs.js:161:11)

    at Object.unlink (fs.js:1151:14)

    at /root/.nvm/versions/node/v14.5.0/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1029:16

    at Array.forEach (<anonymous>)

    at /root/.nvm/versions/node/v14.5.0/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1028:15

    at /root/.nvm/versions/node/v14.5.0/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:940:13

    at testOpenSSLPath (/root/.nvm/versions/node/v14.5.0/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1101:9)

    at spawnOpenSSL (/root/.nvm/versions/node/v14.5.0/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:920:5)

    at spawnWrapper (/root/.nvm/versions/node/v14.5.0/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:1027:5)

    at Object.readCertificateInfo (/root/.nvm/versions/node/v14.5.0/lib/node_modules/beame-insta-ssl/node_modules/pem/lib/pem.js:428:5)

[2020-07-10 20:19:45] [BeameInstaSSL] FATAL: Callback must be a function. Received undefined
```

**Comment by joeyfigaro** [comment]
Also receiving undefined for the callback during registration—can't use, currently.

**Comment by organom** [comment]
Sorry for the late reply on this. 
Can you please try the dev branch? I believe this was already fixed there, but unfortunately we still didn't had enough time to go over the integration tests and release it. Should be stable enough to use and way more up to date.
